name: FreezePlugin
version: 1.0
main: dev.philippcmd.freezeplugin.FreezePlugin
api-version: 1.21
commands:
  freeze:
    description: Freeze or unfreeze a player
    usage: /freeze <player> <time in sec> [freeze/unfreeze]
    permission: freezeplugin.use
    permission-message: You do not have permission to use this command.
permissions:
  freezeplugin.use:
    description: Allows the use of the freeze command.
    default: op


