name: FreezePlugin
main: de.philipp29012010.freezeplugin.FreezePlugin
version: 1.0
api-version: 1.21
commands:
  freeze:
    description: Freezes or unfreezes a player.
    usage: /freeze <player> <freeze/unfreeze>
    permission: op
    permission-message: You do not have permission to use this command.


